name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck
        uses: lunarmodules/luacheck@v0

  stylua:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Stylua
      uses: JohnnyMorganz/stylua-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest
        args: --check .

  unit-tests:
    strategy:
          fail-fast: false
          matrix:
            neovim_repo: [stable, unstable]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo add-apt-repository ppa:neovim-ppa/${{ matrix.neovim_repo }}
          sudo apt update
          sudo apt-get install -y neovim

      - name: Install Coverage Dependencies
        if: ${{ matrix.neovim_repo == 'stable' }}
        run: |
          sudo apt-get install -y luarocks
          sudo luarocks install luacov-coveralls

      - name: Run Tests
        run: nvim -u NONE --headless --cmd "luafile test.lua"

      - name: Upload Coverage
        if: ${{ matrix.neovim_repo == 'stable' }}
        run: |
          luacov-coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}

